trigger:
  tags:
    include:
      - campaign-prod*

pool:
  name: 'Default'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  PROJ: "src/Campaign.Api"
  IMAGE_ID: scr.HARBOR.org/ota/campaign
  RELEASE: "campaign"
  ENV: Production
  
steps:
  - task: ShellScript@2
    inputs:
      scriptPath: "deploy_local_new.sh"
    env:
      KUBECONFIG: ""
      #DOTNET_CLI_HOME: "/root"
      PROJ_DIR: $(PROJ)
      PUB_ENV: "Production"
      IMAGE_ID: $(IMAGE_ID)
      RELEASE: $(RELEASE)
      SLN: "Campaign.sln"
      V: $(Build.SourceBranchName)
